//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public string User_ID { get; set; }
        public string Password { get; set; }
        public string Role { get; set; }
    
        public virtual User_Information User_Information { get; set; }
    }
}
