//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Comments
    {
        public string Movie_Title { get; set; }
        public string User_ID { get; set; }
        public int Rating_Point { get; set; }
        public string Comment { get; set; }
    }
}
