#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cinema
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Cinema")]
	public partial class CinemaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCompany(Company instance);
    partial void UpdateCompany(Company instance);
    partial void DeleteCompany(Company instance);
    partial void InsertMovie(Movie instance);
    partial void UpdateMovie(Movie instance);
    partial void DeleteMovie(Movie instance);
    partial void InsertReservation(Reservation instance);
    partial void UpdateReservation(Reservation instance);
    partial void DeleteReservation(Reservation instance);
    partial void InsertShowTime(ShowTime instance);
    partial void UpdateShowTime(ShowTime instance);
    partial void DeleteShowTime(ShowTime instance);
    partial void InsertRoom(Room instance);
    partial void UpdateRoom(Room instance);
    partial void DeleteRoom(Room instance);
    partial void InsertUser_Information(User_Information instance);
    partial void UpdateUser_Information(User_Information instance);
    partial void DeleteUser_Information(User_Information instance);
    #endregion
		
		public CinemaDataContext() : 
				base(global::Cinema.Properties.Settings.Default.CinemaConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public CinemaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CinemaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CinemaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CinemaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<Company> Companies
		{
			get
			{
				return this.GetTable<Company>();
			}
		}
		
		public System.Data.Linq.Table<Customer> Customers
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<Movie> Movies
		{
			get
			{
				return this.GetTable<Movie>();
			}
		}
		
		public System.Data.Linq.Table<Reservation> Reservations
		{
			get
			{
				return this.GetTable<Reservation>();
			}
		}
		
		public System.Data.Linq.Table<Review> Reviews
		{
			get
			{
				return this.GetTable<Review>();
			}
		}
		
		public System.Data.Linq.Table<ShowTime> ShowTimes
		{
			get
			{
				return this.GetTable<ShowTime>();
			}
		}
		
		public System.Data.Linq.Table<Room> Rooms
		{
			get
			{
				return this.GetTable<Room>();
			}
		}
		
		public System.Data.Linq.Table<User_Information> User_Informations
		{
			get
			{
				return this.GetTable<User_Information>();
			}
		}
		
		public System.Data.Linq.Table<View_AllCustomer> View_AllCustomers
		{
			get
			{
				return this.GetTable<View_AllCustomer>();
			}
		}
		
		public System.Data.Linq.Table<View_AllEmployee> View_AllEmployees
		{
			get
			{
				return this.GetTable<View_AllEmployee>();
			}
		}
		
		public System.Data.Linq.Table<View_ClosedShowing> View_ClosedShowings
		{
			get
			{
				return this.GetTable<View_ClosedShowing>();
			}
		}
		
		public System.Data.Linq.Table<View_ComingShowing> View_ComingShowings
		{
			get
			{
				return this.GetTable<View_ComingShowing>();
			}
		}
		
		public System.Data.Linq.Table<View_Comment> View_Comments
		{
			get
			{
				return this.GetTable<View_Comment>();
			}
		}
		
		public System.Data.Linq.Table<View_ShowingInDay> View_ShowingInDays
		{
			get
			{
				return this.GetTable<View_ShowingInDay>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_AddNewCompany")]
		public int Sp_AddNewCompany([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company_ID", DbType="NVarChar(50)")] string company_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="NVarChar(50)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(50)")] string address)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), company_ID, name, email, phone, address);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_AddNewCustomer")]
		public int Sp_AddNewCustomer([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(50)")] string address, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="NVarChar(50)")] string phone)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID, password, name, email, address, phone);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_AddNewMovie")]
		public int Sp_AddNewMovie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Movie_ID", DbType="NVarChar(50)")] string movie_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Movie_Title", DbType="NVarChar(50)")] string movie_Title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Movie_Cost", DbType="Int")] System.Nullable<int> movie_Cost, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Runtime", DbType="Time")] System.Nullable<System.TimeSpan> runtime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Main_Actor", DbType="NVarChar(50)")] string main_Actor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Director", DbType="NVarChar(50)")] string director, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company_ID", DbType="NVarChar(50)")] string company_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), movie_ID, movie_Title, movie_Cost, runtime, main_Actor, director, company_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_AddNewRoom")]
		public int Sp_AddNewRoom([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Room_ID", DbType="NVarChar(50)")] string room_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaxSeats", DbType="Int")] System.Nullable<int> maxSeats, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Screen_Resolution", DbType="NVarChar(50)")] string screen_Resolution, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Audio_Quality", DbType="NVarChar(50)")] string audio_Quality)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), room_ID, maxSeats, screen_Resolution, audio_Quality);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_AddOrUpdateComment")]
		public int Sp_AddOrUpdateComment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Reservation_ID", DbType="Int")] System.Nullable<int> reservation_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rating_Point", DbType="Int")] System.Nullable<int> rating_Point, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="NVarChar(50)")] string comment)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), reservation_ID, rating_Point, comment);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_DelReservation")]
		public int Sp_DelReservation([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_AddReservation")]
		public int Sp_AddReservation([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="NVarChar(50)")] string iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShowID", DbType="NVarChar(50)")] string showID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Seat", DbType="Int")] System.Nullable<int> seat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, showID, seat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_UpdateCompany")]
		public int Sp_UpdateCompany([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company_ID", DbType="NVarChar(50)")] string company_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(50)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Phone", DbType="NVarChar(50)")] string phone, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Address", DbType="NVarChar(50)")] string address)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), company_ID, name, email, phone, address);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_UpdateMovie")]
		public int Sp_UpdateMovie([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Movie_ID", DbType="NVarChar(50)")] string movie_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Movie_Title", DbType="NVarChar(50)")] string movie_Title, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Movie_Cost", DbType="Int")] System.Nullable<int> movie_Cost, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Runtime", DbType="Time")] System.Nullable<System.TimeSpan> runtime, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Main_Actor", DbType="NVarChar(50)")] string main_Actor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Director", DbType="NVarChar(50)")] string director, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company_ID", DbType="NVarChar(50)")] string company_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), movie_ID, movie_Title, movie_Cost, runtime, main_Actor, director, company_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_UpdateShowTime")]
		public int Sp_UpdateShowTime([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShowTime_ID", DbType="NVarChar(50)")] string showTime_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Movie_ID", DbType="NVarChar(50)")] string movie_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Date", DbType="Date")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Start_Time", DbType="Time")] System.Nullable<System.TimeSpan> start_Time, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Room_ID", DbType="NVarChar(50)")] string room_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), showTime_ID, movie_ID, date, start_Time, room_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_UpdateRoom")]
		public int Sp_UpdateRoom([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Room_ID", DbType="NVarChar(50)")] string room_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MaxSeats", DbType="Int")] System.Nullable<int> maxSeats, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Screen_Resolution", DbType="NVarChar(50)")] string screen_Resolution, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Audio_Quality", DbType="NVarChar(50)")] string audio_Quality)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), room_ID, maxSeats, screen_Resolution, audio_Quality);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Sp_AddNewShowTime")]
		public int Sp_AddNewShowTime([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShowTime_ID", DbType="NVarChar(50)")] string showTime_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Movie_ID", DbType="NVarChar(50)")] string movie_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Date", DbType="Date")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Start_Time", DbType="Time")] System.Nullable<System.TimeSpan> start_Time, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Room_ID", DbType="NVarChar(50)")] string room_ID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), showTime_ID, movie_ID, date, start_Time, room_ID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Fn_AdminLogin", IsComposable=true)]
		public IQueryable<Fn_AdminLoginResult> Fn_AdminLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password)
		{
			return this.CreateMethodCallQuery<Fn_AdminLoginResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID, password);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Fn_CustomerLogin", IsComposable=true)]
		public IQueryable<Fn_CustomerLoginResult> Fn_CustomerLogin([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="NVarChar(50)")] string password)
		{
			return this.CreateMethodCallQuery<Fn_CustomerLoginResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID, password);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Fn_BookedSeats", IsComposable=true)]
		public IQueryable<Fn_BookedSeatsResult> Fn_BookedSeats([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShowTime_ID", DbType="NVarChar(50)")] string showTime_ID)
		{
			return this.CreateMethodCallQuery<Fn_BookedSeatsResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), showTime_ID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Fn_ShowTimeByActor", IsComposable=true)]
		public IQueryable<Fn_ShowTimeByActorResult> Fn_ShowTimeByActor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Actor_Name", DbType="NVarChar(50)")] string actor_Name)
		{
			return this.CreateMethodCallQuery<Fn_ShowTimeByActorResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), actor_Name);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Fn_ShowTimeByCompany", IsComposable=true)]
		public IQueryable<Fn_ShowTimeByCompanyResult> Fn_ShowTimeByCompany([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Company", DbType="NVarChar(50)")] string company)
		{
			return this.CreateMethodCallQuery<Fn_ShowTimeByCompanyResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), company);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Fn_ShowTimeByScreen", IsComposable=true)]
		public IQueryable<Fn_ShowTimeByScreenResult> Fn_ShowTimeByScreen([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Screen_Resolution", DbType="NVarChar(50)")] string screen_Resolution)
		{
			return this.CreateMethodCallQuery<Fn_ShowTimeByScreenResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), screen_Resolution);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Fn_SumTotalCost", IsComposable=true)]
		public IQueryable<Fn_SumTotalCostResult> Fn_SumTotalCost([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShowTime_ID", DbType="NVarChar(50)")] string showTime_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Count", DbType="Int")] System.Nullable<int> count)
		{
			return this.CreateMethodCallQuery<Fn_SumTotalCostResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), showTime_ID, user_ID, count);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Fn_UserBooked", IsComposable=true)]
		public IQueryable<Fn_UserBookedResult> Fn_UserBooked([global::System.Data.Linq.Mapping.ParameterAttribute(Name="User_ID", DbType="NVarChar(50)")] string user_ID)
		{
			return this.CreateMethodCallQuery<Fn_UserBookedResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), user_ID);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Fn_UserCommented", IsComposable=true)]
		public IQueryable<Fn_UserCommentedResult> Fn_UserCommented([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="NVarChar(50)")] string iD)
		{
			return this.CreateMethodCallQuery<Fn_UserCommentedResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Fn_UserInformation", IsComposable=true)]
		public IQueryable<Fn_UserInformationResult> Fn_UserInformation([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="NVarChar(50)")] string iD)
		{
			return this.CreateMethodCallQuery<Fn_UserInformationResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin
	{
		
		private string _User_ID;
		
		private string _Password;
		
		private string _Role;
		
		public Admin()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this._User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this._Role = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Company")]
	public partial class Company : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Company_ID;
		
		private string _Name;
		
		private string _Email;
		
		private string _Phone;
		
		private string _Address;
		
		private EntitySet<Movie> _Movies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCompany_IDChanging(string value);
    partial void OnCompany_IDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    #endregion
		
		public Company()
		{
			this._Movies = new EntitySet<Movie>(new Action<Movie>(this.attach_Movies), new Action<Movie>(this.detach_Movies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Company_ID
		{
			get
			{
				return this._Company_ID;
			}
			set
			{
				if ((this._Company_ID != value))
				{
					this.OnCompany_IDChanging(value);
					this.SendPropertyChanging();
					this._Company_ID = value;
					this.SendPropertyChanged("Company_ID");
					this.OnCompany_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_Movie", Storage="_Movies", ThisKey="Company_ID", OtherKey="Company_ID")]
		public EntitySet<Movie> Movies
		{
			get
			{
				return this._Movies;
			}
			set
			{
				this._Movies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Movies(Movie entity)
		{
			this.SendPropertyChanging();
			entity.Company = this;
		}
		
		private void detach_Movies(Movie entity)
		{
			this.SendPropertyChanging();
			entity.Company = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer
	{
		
		private string _User_ID;
		
		private string _Password;
		
		private int _Balance;
		
		private int _Point;
		
		private bool _isVIP;
		
		public Customer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this._User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this._Password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Int NOT NULL")]
		public int Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Point", DbType="Int NOT NULL")]
		public int Point
		{
			get
			{
				return this._Point;
			}
			set
			{
				if ((this._Point != value))
				{
					this._Point = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isVIP", DbType="Bit NOT NULL")]
		public bool isVIP
		{
			get
			{
				return this._isVIP;
			}
			set
			{
				if ((this._isVIP != value))
				{
					this._isVIP = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Movie")]
	public partial class Movie : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Movie_ID;
		
		private string _Movie_Title;
		
		private int _Movie_Cost;
		
		private System.TimeSpan _Runtime;
		
		private string _Main_Actor;
		
		private string _Director;
		
		private string _Company_ID;
		
		private EntitySet<ShowTime> _ShowTimes;
		
		private EntityRef<Company> _Company;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMovie_IDChanging(string value);
    partial void OnMovie_IDChanged();
    partial void OnMovie_TitleChanging(string value);
    partial void OnMovie_TitleChanged();
    partial void OnMovie_CostChanging(int value);
    partial void OnMovie_CostChanged();
    partial void OnRuntimeChanging(System.TimeSpan value);
    partial void OnRuntimeChanged();
    partial void OnMain_ActorChanging(string value);
    partial void OnMain_ActorChanged();
    partial void OnDirectorChanging(string value);
    partial void OnDirectorChanged();
    partial void OnCompany_IDChanging(string value);
    partial void OnCompany_IDChanged();
    #endregion
		
		public Movie()
		{
			this._ShowTimes = new EntitySet<ShowTime>(new Action<ShowTime>(this.attach_ShowTimes), new Action<ShowTime>(this.detach_ShowTimes));
			this._Company = default(EntityRef<Company>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Movie_ID
		{
			get
			{
				return this._Movie_ID;
			}
			set
			{
				if ((this._Movie_ID != value))
				{
					this.OnMovie_IDChanging(value);
					this.SendPropertyChanging();
					this._Movie_ID = value;
					this.SendPropertyChanged("Movie_ID");
					this.OnMovie_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Movie_Title
		{
			get
			{
				return this._Movie_Title;
			}
			set
			{
				if ((this._Movie_Title != value))
				{
					this.OnMovie_TitleChanging(value);
					this.SendPropertyChanging();
					this._Movie_Title = value;
					this.SendPropertyChanged("Movie_Title");
					this.OnMovie_TitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_Cost", DbType="Int NOT NULL")]
		public int Movie_Cost
		{
			get
			{
				return this._Movie_Cost;
			}
			set
			{
				if ((this._Movie_Cost != value))
				{
					this.OnMovie_CostChanging(value);
					this.SendPropertyChanging();
					this._Movie_Cost = value;
					this.SendPropertyChanged("Movie_Cost");
					this.OnMovie_CostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Runtime", DbType="Time NOT NULL")]
		public System.TimeSpan Runtime
		{
			get
			{
				return this._Runtime;
			}
			set
			{
				if ((this._Runtime != value))
				{
					this.OnRuntimeChanging(value);
					this.SendPropertyChanging();
					this._Runtime = value;
					this.SendPropertyChanged("Runtime");
					this.OnRuntimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Main_Actor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Main_Actor
		{
			get
			{
				return this._Main_Actor;
			}
			set
			{
				if ((this._Main_Actor != value))
				{
					this.OnMain_ActorChanging(value);
					this.SendPropertyChanging();
					this._Main_Actor = value;
					this.SendPropertyChanged("Main_Actor");
					this.OnMain_ActorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Director", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Director
		{
			get
			{
				return this._Director;
			}
			set
			{
				if ((this._Director != value))
				{
					this.OnDirectorChanging(value);
					this.SendPropertyChanging();
					this._Director = value;
					this.SendPropertyChanged("Director");
					this.OnDirectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Company_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Company_ID
		{
			get
			{
				return this._Company_ID;
			}
			set
			{
				if ((this._Company_ID != value))
				{
					if (this._Company.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCompany_IDChanging(value);
					this.SendPropertyChanging();
					this._Company_ID = value;
					this.SendPropertyChanged("Company_ID");
					this.OnCompany_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Movie_ShowTime", Storage="_ShowTimes", ThisKey="Movie_ID", OtherKey="Movie_ID")]
		public EntitySet<ShowTime> ShowTimes
		{
			get
			{
				return this._ShowTimes;
			}
			set
			{
				this._ShowTimes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Company_Movie", Storage="_Company", ThisKey="Company_ID", OtherKey="Company_ID", IsForeignKey=true)]
		public Company Company
		{
			get
			{
				return this._Company.Entity;
			}
			set
			{
				Company previousValue = this._Company.Entity;
				if (((previousValue != value) 
							|| (this._Company.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Company.Entity = null;
						previousValue.Movies.Remove(this);
					}
					this._Company.Entity = value;
					if ((value != null))
					{
						value.Movies.Add(this);
						this._Company_ID = value.Company_ID;
					}
					else
					{
						this._Company_ID = default(string);
					}
					this.SendPropertyChanged("Company");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ShowTimes(ShowTime entity)
		{
			this.SendPropertyChanging();
			entity.Movie = this;
		}
		
		private void detach_ShowTimes(ShowTime entity)
		{
			this.SendPropertyChanging();
			entity.Movie = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Reservation")]
	public partial class Reservation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Reservation_ID;
		
		private string _User_ID;
		
		private string _ShowTime_ID;
		
		private int _Seat;
		
		private System.Nullable<int> _Paid;
		
		private EntityRef<ShowTime> _ShowTime;
		
		private EntityRef<User_Information> _User_Information;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnReservation_IDChanging(int value);
    partial void OnReservation_IDChanged();
    partial void OnUser_IDChanging(string value);
    partial void OnUser_IDChanged();
    partial void OnShowTime_IDChanging(string value);
    partial void OnShowTime_IDChanged();
    partial void OnSeatChanging(int value);
    partial void OnSeatChanged();
    partial void OnPaidChanging(System.Nullable<int> value);
    partial void OnPaidChanged();
    #endregion
		
		public Reservation()
		{
			this._ShowTime = default(EntityRef<ShowTime>);
			this._User_Information = default(EntityRef<User_Information>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reservation_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Reservation_ID
		{
			get
			{
				return this._Reservation_ID;
			}
			set
			{
				if ((this._Reservation_ID != value))
				{
					this.OnReservation_IDChanging(value);
					this.SendPropertyChanging();
					this._Reservation_ID = value;
					this.SendPropertyChanged("Reservation_ID");
					this.OnReservation_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					if (this._User_Information.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowTime_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ShowTime_ID
		{
			get
			{
				return this._ShowTime_ID;
			}
			set
			{
				if ((this._ShowTime_ID != value))
				{
					if (this._ShowTime.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnShowTime_IDChanging(value);
					this.SendPropertyChanging();
					this._ShowTime_ID = value;
					this.SendPropertyChanged("ShowTime_ID");
					this.OnShowTime_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seat", DbType="Int NOT NULL")]
		public int Seat
		{
			get
			{
				return this._Seat;
			}
			set
			{
				if ((this._Seat != value))
				{
					this.OnSeatChanging(value);
					this.SendPropertyChanging();
					this._Seat = value;
					this.SendPropertyChanged("Seat");
					this.OnSeatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Paid", DbType="Int")]
		public System.Nullable<int> Paid
		{
			get
			{
				return this._Paid;
			}
			set
			{
				if ((this._Paid != value))
				{
					this.OnPaidChanging(value);
					this.SendPropertyChanging();
					this._Paid = value;
					this.SendPropertyChanged("Paid");
					this.OnPaidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ShowTime_Reservation", Storage="_ShowTime", ThisKey="ShowTime_ID", OtherKey="ShowTime_ID", IsForeignKey=true)]
		public ShowTime ShowTime
		{
			get
			{
				return this._ShowTime.Entity;
			}
			set
			{
				ShowTime previousValue = this._ShowTime.Entity;
				if (((previousValue != value) 
							|| (this._ShowTime.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ShowTime.Entity = null;
						previousValue.Reservations.Remove(this);
					}
					this._ShowTime.Entity = value;
					if ((value != null))
					{
						value.Reservations.Add(this);
						this._ShowTime_ID = value.ShowTime_ID;
					}
					else
					{
						this._ShowTime_ID = default(string);
					}
					this.SendPropertyChanged("ShowTime");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Information_Reservation", Storage="_User_Information", ThisKey="User_ID", OtherKey="User_ID", IsForeignKey=true)]
		public User_Information User_Information
		{
			get
			{
				return this._User_Information.Entity;
			}
			set
			{
				User_Information previousValue = this._User_Information.Entity;
				if (((previousValue != value) 
							|| (this._User_Information.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._User_Information.Entity = null;
						previousValue.Reservations.Remove(this);
					}
					this._User_Information.Entity = value;
					if ((value != null))
					{
						value.Reservations.Add(this);
						this._User_ID = value.User_ID;
					}
					else
					{
						this._User_ID = default(string);
					}
					this.SendPropertyChanged("User_Information");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Review")]
	public partial class Review
	{
		
		private int _Reservation_ID;
		
		private int _Rating_Point;
		
		private string _Comment;
		
		public Review()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reservation_ID", DbType="Int NOT NULL")]
		public int Reservation_ID
		{
			get
			{
				return this._Reservation_ID;
			}
			set
			{
				if ((this._Reservation_ID != value))
				{
					this._Reservation_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Point", DbType="Int NOT NULL")]
		public int Rating_Point
		{
			get
			{
				return this._Rating_Point;
			}
			set
			{
				if ((this._Rating_Point != value))
				{
					this._Rating_Point = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(50)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ShowTime")]
	public partial class ShowTime : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ShowTime_ID;
		
		private string _Movie_ID;
		
		private System.DateTime _Date;
		
		private System.TimeSpan _Start_Time;
		
		private System.Nullable<System.TimeSpan> _End_Time;
		
		private int _Current_Seats;
		
		private System.Nullable<int> _Quality_Cost;
		
		private System.Nullable<int> _Total_Cost;
		
		private string _Room_ID;
		
		private EntitySet<Reservation> _Reservations;
		
		private EntityRef<Movie> _Movie;
		
		private EntityRef<Room> _Room;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnShowTime_IDChanging(string value);
    partial void OnShowTime_IDChanged();
    partial void OnMovie_IDChanging(string value);
    partial void OnMovie_IDChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnStart_TimeChanging(System.TimeSpan value);
    partial void OnStart_TimeChanged();
    partial void OnEnd_TimeChanging(System.Nullable<System.TimeSpan> value);
    partial void OnEnd_TimeChanged();
    partial void OnCurrent_SeatsChanging(int value);
    partial void OnCurrent_SeatsChanged();
    partial void OnQuality_CostChanging(System.Nullable<int> value);
    partial void OnQuality_CostChanged();
    partial void OnTotal_CostChanging(System.Nullable<int> value);
    partial void OnTotal_CostChanged();
    partial void OnRoom_IDChanging(string value);
    partial void OnRoom_IDChanged();
    #endregion
		
		public ShowTime()
		{
			this._Reservations = new EntitySet<Reservation>(new Action<Reservation>(this.attach_Reservations), new Action<Reservation>(this.detach_Reservations));
			this._Movie = default(EntityRef<Movie>);
			this._Room = default(EntityRef<Room>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowTime_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ShowTime_ID
		{
			get
			{
				return this._ShowTime_ID;
			}
			set
			{
				if ((this._ShowTime_ID != value))
				{
					this.OnShowTime_IDChanging(value);
					this.SendPropertyChanging();
					this._ShowTime_ID = value;
					this.SendPropertyChanged("ShowTime_ID");
					this.OnShowTime_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Movie_ID
		{
			get
			{
				return this._Movie_ID;
			}
			set
			{
				if ((this._Movie_ID != value))
				{
					if (this._Movie.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMovie_IDChanging(value);
					this.SendPropertyChanging();
					this._Movie_ID = value;
					this.SendPropertyChanged("Movie_ID");
					this.OnMovie_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Time", DbType="Time NOT NULL")]
		public System.TimeSpan Start_Time
		{
			get
			{
				return this._Start_Time;
			}
			set
			{
				if ((this._Start_Time != value))
				{
					this.OnStart_TimeChanging(value);
					this.SendPropertyChanging();
					this._Start_Time = value;
					this.SendPropertyChanged("Start_Time");
					this.OnStart_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> End_Time
		{
			get
			{
				return this._End_Time;
			}
			set
			{
				if ((this._End_Time != value))
				{
					this.OnEnd_TimeChanging(value);
					this.SendPropertyChanging();
					this._End_Time = value;
					this.SendPropertyChanged("End_Time");
					this.OnEnd_TimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Current_Seats", DbType="Int NOT NULL")]
		public int Current_Seats
		{
			get
			{
				return this._Current_Seats;
			}
			set
			{
				if ((this._Current_Seats != value))
				{
					this.OnCurrent_SeatsChanging(value);
					this.SendPropertyChanging();
					this._Current_Seats = value;
					this.SendPropertyChanged("Current_Seats");
					this.OnCurrent_SeatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quality_Cost", DbType="Int")]
		public System.Nullable<int> Quality_Cost
		{
			get
			{
				return this._Quality_Cost;
			}
			set
			{
				if ((this._Quality_Cost != value))
				{
					this.OnQuality_CostChanging(value);
					this.SendPropertyChanging();
					this._Quality_Cost = value;
					this.SendPropertyChanged("Quality_Cost");
					this.OnQuality_CostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Cost", DbType="Int")]
		public System.Nullable<int> Total_Cost
		{
			get
			{
				return this._Total_Cost;
			}
			set
			{
				if ((this._Total_Cost != value))
				{
					this.OnTotal_CostChanging(value);
					this.SendPropertyChanging();
					this._Total_Cost = value;
					this.SendPropertyChanged("Total_Cost");
					this.OnTotal_CostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Room_ID
		{
			get
			{
				return this._Room_ID;
			}
			set
			{
				if ((this._Room_ID != value))
				{
					if (this._Room.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnRoom_IDChanging(value);
					this.SendPropertyChanging();
					this._Room_ID = value;
					this.SendPropertyChanged("Room_ID");
					this.OnRoom_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ShowTime_Reservation", Storage="_Reservations", ThisKey="ShowTime_ID", OtherKey="ShowTime_ID")]
		public EntitySet<Reservation> Reservations
		{
			get
			{
				return this._Reservations;
			}
			set
			{
				this._Reservations.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Movie_ShowTime", Storage="_Movie", ThisKey="Movie_ID", OtherKey="Movie_ID", IsForeignKey=true)]
		public Movie Movie
		{
			get
			{
				return this._Movie.Entity;
			}
			set
			{
				Movie previousValue = this._Movie.Entity;
				if (((previousValue != value) 
							|| (this._Movie.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Movie.Entity = null;
						previousValue.ShowTimes.Remove(this);
					}
					this._Movie.Entity = value;
					if ((value != null))
					{
						value.ShowTimes.Add(this);
						this._Movie_ID = value.Movie_ID;
					}
					else
					{
						this._Movie_ID = default(string);
					}
					this.SendPropertyChanged("Movie");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Room_ShowTime", Storage="_Room", ThisKey="Room_ID", OtherKey="Room_ID", IsForeignKey=true)]
		public Room Room
		{
			get
			{
				return this._Room.Entity;
			}
			set
			{
				Room previousValue = this._Room.Entity;
				if (((previousValue != value) 
							|| (this._Room.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Room.Entity = null;
						previousValue.ShowTimes.Remove(this);
					}
					this._Room.Entity = value;
					if ((value != null))
					{
						value.ShowTimes.Add(this);
						this._Room_ID = value.Room_ID;
					}
					else
					{
						this._Room_ID = default(string);
					}
					this.SendPropertyChanged("Room");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Reservations(Reservation entity)
		{
			this.SendPropertyChanging();
			entity.ShowTime = this;
		}
		
		private void detach_Reservations(Reservation entity)
		{
			this.SendPropertyChanging();
			entity.ShowTime = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Room")]
	public partial class Room : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Room_ID;
		
		private int _MaxSeats;
		
		private string _Screen_Resolution;
		
		private string _Audio_Quality;
		
		private EntitySet<ShowTime> _ShowTimes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRoom_IDChanging(string value);
    partial void OnRoom_IDChanged();
    partial void OnMaxSeatsChanging(int value);
    partial void OnMaxSeatsChanged();
    partial void OnScreen_ResolutionChanging(string value);
    partial void OnScreen_ResolutionChanged();
    partial void OnAudio_QualityChanging(string value);
    partial void OnAudio_QualityChanged();
    #endregion
		
		public Room()
		{
			this._ShowTimes = new EntitySet<ShowTime>(new Action<ShowTime>(this.attach_ShowTimes), new Action<ShowTime>(this.detach_ShowTimes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Room_ID
		{
			get
			{
				return this._Room_ID;
			}
			set
			{
				if ((this._Room_ID != value))
				{
					this.OnRoom_IDChanging(value);
					this.SendPropertyChanging();
					this._Room_ID = value;
					this.SendPropertyChanged("Room_ID");
					this.OnRoom_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaxSeats", DbType="Int NOT NULL")]
		public int MaxSeats
		{
			get
			{
				return this._MaxSeats;
			}
			set
			{
				if ((this._MaxSeats != value))
				{
					this.OnMaxSeatsChanging(value);
					this.SendPropertyChanging();
					this._MaxSeats = value;
					this.SendPropertyChanged("MaxSeats");
					this.OnMaxSeatsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Screen_Resolution", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Screen_Resolution
		{
			get
			{
				return this._Screen_Resolution;
			}
			set
			{
				if ((this._Screen_Resolution != value))
				{
					this.OnScreen_ResolutionChanging(value);
					this.SendPropertyChanging();
					this._Screen_Resolution = value;
					this.SendPropertyChanged("Screen_Resolution");
					this.OnScreen_ResolutionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Audio_Quality", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Audio_Quality
		{
			get
			{
				return this._Audio_Quality;
			}
			set
			{
				if ((this._Audio_Quality != value))
				{
					this.OnAudio_QualityChanging(value);
					this.SendPropertyChanging();
					this._Audio_Quality = value;
					this.SendPropertyChanged("Audio_Quality");
					this.OnAudio_QualityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Room_ShowTime", Storage="_ShowTimes", ThisKey="Room_ID", OtherKey="Room_ID")]
		public EntitySet<ShowTime> ShowTimes
		{
			get
			{
				return this._ShowTimes;
			}
			set
			{
				this._ShowTimes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ShowTimes(ShowTime entity)
		{
			this.SendPropertyChanging();
			entity.Room = this;
		}
		
		private void detach_ShowTimes(ShowTime entity)
		{
			this.SendPropertyChanging();
			entity.Room = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Information")]
	public partial class User_Information : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _User_ID;
		
		private string _Name;
		
		private string _Email;
		
		private string _Address;
		
		private string _Phone;
		
		private EntitySet<Reservation> _Reservations;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUser_IDChanging(string value);
    partial void OnUser_IDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    #endregion
		
		public User_Information()
		{
			this._Reservations = new EntitySet<Reservation>(new Action<Reservation>(this.attach_Reservations), new Action<Reservation>(this.detach_Reservations));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this.OnUser_IDChanging(value);
					this.SendPropertyChanging();
					this._User_ID = value;
					this.SendPropertyChanged("User_ID");
					this.OnUser_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="User_Information_Reservation", Storage="_Reservations", ThisKey="User_ID", OtherKey="User_ID")]
		public EntitySet<Reservation> Reservations
		{
			get
			{
				return this._Reservations;
			}
			set
			{
				this._Reservations.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Reservations(Reservation entity)
		{
			this.SendPropertyChanging();
			entity.User_Information = this;
		}
		
		private void detach_Reservations(Reservation entity)
		{
			this.SendPropertyChanging();
			entity.User_Information = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_AllCustomers")]
	public partial class View_AllCustomer
	{
		
		private string _User_ID;
		
		private string _Name;
		
		private string _Email;
		
		private string _Address;
		
		private string _Phone;
		
		private int _Point;
		
		private bool _isVip;
		
		public View_AllCustomer()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this._User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Point", DbType="Int NOT NULL")]
		public int Point
		{
			get
			{
				return this._Point;
			}
			set
			{
				if ((this._Point != value))
				{
					this._Point = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isVip", DbType="Bit NOT NULL")]
		public bool isVip
		{
			get
			{
				return this._isVip;
			}
			set
			{
				if ((this._isVip != value))
				{
					this._isVip = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_AllEmployees")]
	public partial class View_AllEmployee
	{
		
		private string _User_ID;
		
		private string _Name;
		
		private string _Email;
		
		private string _Address;
		
		private string _Phone;
		
		private string _Role;
		
		public View_AllEmployee()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this._User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this._Address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this._Phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this._Role = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_ClosedShowing")]
	public partial class View_ClosedShowing
	{
		
		private string _ShowTime_ID;
		
		private string _Movie_Title;
		
		private System.Nullable<int> _Total_Cost;
		
		private string _Main_Actor;
		
		private string _Director;
		
		private System.DateTime _Date;
		
		private System.TimeSpan _Start_Time;
		
		private System.Nullable<System.TimeSpan> _End_Time;
		
		public View_ClosedShowing()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowTime_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ShowTime_ID
		{
			get
			{
				return this._ShowTime_ID;
			}
			set
			{
				if ((this._ShowTime_ID != value))
				{
					this._ShowTime_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Movie_Title
		{
			get
			{
				return this._Movie_Title;
			}
			set
			{
				if ((this._Movie_Title != value))
				{
					this._Movie_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Cost", DbType="Int")]
		public System.Nullable<int> Total_Cost
		{
			get
			{
				return this._Total_Cost;
			}
			set
			{
				if ((this._Total_Cost != value))
				{
					this._Total_Cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Main_Actor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Main_Actor
		{
			get
			{
				return this._Main_Actor;
			}
			set
			{
				if ((this._Main_Actor != value))
				{
					this._Main_Actor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Director", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Director
		{
			get
			{
				return this._Director;
			}
			set
			{
				if ((this._Director != value))
				{
					this._Director = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Time", DbType="Time NOT NULL")]
		public System.TimeSpan Start_Time
		{
			get
			{
				return this._Start_Time;
			}
			set
			{
				if ((this._Start_Time != value))
				{
					this._Start_Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> End_Time
		{
			get
			{
				return this._End_Time;
			}
			set
			{
				if ((this._End_Time != value))
				{
					this._End_Time = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_ComingShowing")]
	public partial class View_ComingShowing
	{
		
		private string _ShowTime_ID;
		
		private string _Movie_Title;
		
		private System.Nullable<int> _Total_Cost;
		
		private string _Main_Actor;
		
		private string _Director;
		
		private System.DateTime _Date;
		
		private System.TimeSpan _Start_Time;
		
		private System.Nullable<System.TimeSpan> _End_Time;
		
		public View_ComingShowing()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowTime_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ShowTime_ID
		{
			get
			{
				return this._ShowTime_ID;
			}
			set
			{
				if ((this._ShowTime_ID != value))
				{
					this._ShowTime_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Movie_Title
		{
			get
			{
				return this._Movie_Title;
			}
			set
			{
				if ((this._Movie_Title != value))
				{
					this._Movie_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Cost", DbType="Int")]
		public System.Nullable<int> Total_Cost
		{
			get
			{
				return this._Total_Cost;
			}
			set
			{
				if ((this._Total_Cost != value))
				{
					this._Total_Cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Main_Actor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Main_Actor
		{
			get
			{
				return this._Main_Actor;
			}
			set
			{
				if ((this._Main_Actor != value))
				{
					this._Main_Actor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Director", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Director
		{
			get
			{
				return this._Director;
			}
			set
			{
				if ((this._Director != value))
				{
					this._Director = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Time", DbType="Time NOT NULL")]
		public System.TimeSpan Start_Time
		{
			get
			{
				return this._Start_Time;
			}
			set
			{
				if ((this._Start_Time != value))
				{
					this._Start_Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> End_Time
		{
			get
			{
				return this._End_Time;
			}
			set
			{
				if ((this._End_Time != value))
				{
					this._End_Time = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_Comments")]
	public partial class View_Comment
	{
		
		private string _Movie_Title;
		
		private string _User_ID;
		
		private int _Rating_Point;
		
		private string _Comment;
		
		public View_Comment()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Movie_Title
		{
			get
			{
				return this._Movie_Title;
			}
			set
			{
				if ((this._Movie_Title != value))
				{
					this._Movie_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this._User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Point", DbType="Int NOT NULL")]
		public int Rating_Point
		{
			get
			{
				return this._Rating_Point;
			}
			set
			{
				if ((this._Rating_Point != value))
				{
					this._Rating_Point = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(50)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.View_ShowingInDay")]
	public partial class View_ShowingInDay
	{
		
		private string _ShowTime_ID;
		
		private string _Movie_Title;
		
		private System.Nullable<int> _Total_Cost;
		
		private string _Main_Actor;
		
		private string _Director;
		
		private System.DateTime _Date;
		
		private System.TimeSpan _Start_Time;
		
		private System.Nullable<System.TimeSpan> _End_Time;
		
		public View_ShowingInDay()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowTime_ID", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ShowTime_ID
		{
			get
			{
				return this._ShowTime_ID;
			}
			set
			{
				if ((this._ShowTime_ID != value))
				{
					this._ShowTime_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_Title", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Movie_Title
		{
			get
			{
				return this._Movie_Title;
			}
			set
			{
				if ((this._Movie_Title != value))
				{
					this._Movie_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Cost", DbType="Int")]
		public System.Nullable<int> Total_Cost
		{
			get
			{
				return this._Total_Cost;
			}
			set
			{
				if ((this._Total_Cost != value))
				{
					this._Total_Cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Main_Actor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Main_Actor
		{
			get
			{
				return this._Main_Actor;
			}
			set
			{
				if ((this._Main_Actor != value))
				{
					this._Main_Actor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Director", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Director
		{
			get
			{
				return this._Director;
			}
			set
			{
				if ((this._Director != value))
				{
					this._Director = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Time", DbType="Time NOT NULL")]
		public System.TimeSpan Start_Time
		{
			get
			{
				return this._Start_Time;
			}
			set
			{
				if ((this._Start_Time != value))
				{
					this._Start_Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> End_Time
		{
			get
			{
				return this._End_Time;
			}
			set
			{
				if ((this._End_Time != value))
				{
					this._End_Time = value;
				}
			}
		}
	}
	
	public partial class Fn_AdminLoginResult
	{
		
		private string _User_ID;
		
		private string _User_Name;
		
		private string _Admin_Role;
		
		public Fn_AdminLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50)")]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this._User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="NVarChar(50)")]
		public string User_Name
		{
			get
			{
				return this._User_Name;
			}
			set
			{
				if ((this._User_Name != value))
				{
					this._User_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Admin_Role", DbType="NVarChar(50)")]
		public string Admin_Role
		{
			get
			{
				return this._Admin_Role;
			}
			set
			{
				if ((this._Admin_Role != value))
				{
					this._Admin_Role = value;
				}
			}
		}
	}
	
	public partial class Fn_CustomerLoginResult
	{
		
		private string _User_ID;
		
		private string _User_Name;
		
		private System.Nullable<int> _Balance;
		
		private System.Nullable<int> _Point;
		
		private System.Nullable<bool> _isVip;
		
		public Fn_CustomerLoginResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_ID", DbType="NVarChar(50)")]
		public string User_ID
		{
			get
			{
				return this._User_ID;
			}
			set
			{
				if ((this._User_ID != value))
				{
					this._User_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_User_Name", DbType="NVarChar(50)")]
		public string User_Name
		{
			get
			{
				return this._User_Name;
			}
			set
			{
				if ((this._User_Name != value))
				{
					this._User_Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Int")]
		public System.Nullable<int> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Point", DbType="Int")]
		public System.Nullable<int> Point
		{
			get
			{
				return this._Point;
			}
			set
			{
				if ((this._Point != value))
				{
					this._Point = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isVip", DbType="Bit")]
		public System.Nullable<bool> isVip
		{
			get
			{
				return this._isVip;
			}
			set
			{
				if ((this._isVip != value))
				{
					this._isVip = value;
				}
			}
		}
	}
	
	public partial class Fn_BookedSeatsResult
	{
		
		private System.Nullable<int> _Seat;
		
		public Fn_BookedSeatsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seat", DbType="Int")]
		public System.Nullable<int> Seat
		{
			get
			{
				return this._Seat;
			}
			set
			{
				if ((this._Seat != value))
				{
					this._Seat = value;
				}
			}
		}
	}
	
	public partial class Fn_ShowTimeByActorResult
	{
		
		private string _ShowTime_ID;
		
		private string _Movie_Title;
		
		private System.Nullable<int> _Total_Cost;
		
		private string _Main_Actor;
		
		private string _Director;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<System.TimeSpan> _Start_Time;
		
		private System.Nullable<System.TimeSpan> _End_Time;
		
		public Fn_ShowTimeByActorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowTime_ID", DbType="NVarChar(50)")]
		public string ShowTime_ID
		{
			get
			{
				return this._ShowTime_ID;
			}
			set
			{
				if ((this._ShowTime_ID != value))
				{
					this._ShowTime_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_Title", DbType="NVarChar(50)")]
		public string Movie_Title
		{
			get
			{
				return this._Movie_Title;
			}
			set
			{
				if ((this._Movie_Title != value))
				{
					this._Movie_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Cost", DbType="Int")]
		public System.Nullable<int> Total_Cost
		{
			get
			{
				return this._Total_Cost;
			}
			set
			{
				if ((this._Total_Cost != value))
				{
					this._Total_Cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Main_Actor", DbType="NVarChar(50)")]
		public string Main_Actor
		{
			get
			{
				return this._Main_Actor;
			}
			set
			{
				if ((this._Main_Actor != value))
				{
					this._Main_Actor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Director", DbType="NVarChar(50)")]
		public string Director
		{
			get
			{
				return this._Director;
			}
			set
			{
				if ((this._Director != value))
				{
					this._Director = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> Start_Time
		{
			get
			{
				return this._Start_Time;
			}
			set
			{
				if ((this._Start_Time != value))
				{
					this._Start_Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> End_Time
		{
			get
			{
				return this._End_Time;
			}
			set
			{
				if ((this._End_Time != value))
				{
					this._End_Time = value;
				}
			}
		}
	}
	
	public partial class Fn_ShowTimeByCompanyResult
	{
		
		private string _ShowTime_ID;
		
		private string _Movie_Title;
		
		private System.Nullable<int> _Total_Cost;
		
		private string _Main_Actor;
		
		private string _Director;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<System.TimeSpan> _Start_Time;
		
		private System.Nullable<System.TimeSpan> _End_Time;
		
		public Fn_ShowTimeByCompanyResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowTime_ID", DbType="NVarChar(50)")]
		public string ShowTime_ID
		{
			get
			{
				return this._ShowTime_ID;
			}
			set
			{
				if ((this._ShowTime_ID != value))
				{
					this._ShowTime_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_Title", DbType="NVarChar(50)")]
		public string Movie_Title
		{
			get
			{
				return this._Movie_Title;
			}
			set
			{
				if ((this._Movie_Title != value))
				{
					this._Movie_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Cost", DbType="Int")]
		public System.Nullable<int> Total_Cost
		{
			get
			{
				return this._Total_Cost;
			}
			set
			{
				if ((this._Total_Cost != value))
				{
					this._Total_Cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Main_Actor", DbType="NVarChar(50)")]
		public string Main_Actor
		{
			get
			{
				return this._Main_Actor;
			}
			set
			{
				if ((this._Main_Actor != value))
				{
					this._Main_Actor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Director", DbType="NVarChar(50)")]
		public string Director
		{
			get
			{
				return this._Director;
			}
			set
			{
				if ((this._Director != value))
				{
					this._Director = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> Start_Time
		{
			get
			{
				return this._Start_Time;
			}
			set
			{
				if ((this._Start_Time != value))
				{
					this._Start_Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> End_Time
		{
			get
			{
				return this._End_Time;
			}
			set
			{
				if ((this._End_Time != value))
				{
					this._End_Time = value;
				}
			}
		}
	}
	
	public partial class Fn_ShowTimeByScreenResult
	{
		
		private string _ShowTime_ID;
		
		private string _Movie_Title;
		
		private System.Nullable<int> _Total_Cost;
		
		private string _Main_Actor;
		
		private string _Director;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<System.TimeSpan> _Start_Time;
		
		private System.Nullable<System.TimeSpan> _End_Time;
		
		public Fn_ShowTimeByScreenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShowTime_ID", DbType="NVarChar(50)")]
		public string ShowTime_ID
		{
			get
			{
				return this._ShowTime_ID;
			}
			set
			{
				if ((this._ShowTime_ID != value))
				{
					this._ShowTime_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_Title", DbType="NVarChar(50)")]
		public string Movie_Title
		{
			get
			{
				return this._Movie_Title;
			}
			set
			{
				if ((this._Movie_Title != value))
				{
					this._Movie_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total_Cost", DbType="Int")]
		public System.Nullable<int> Total_Cost
		{
			get
			{
				return this._Total_Cost;
			}
			set
			{
				if ((this._Total_Cost != value))
				{
					this._Total_Cost = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Main_Actor", DbType="NVarChar(50)")]
		public string Main_Actor
		{
			get
			{
				return this._Main_Actor;
			}
			set
			{
				if ((this._Main_Actor != value))
				{
					this._Main_Actor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Director", DbType="NVarChar(50)")]
		public string Director
		{
			get
			{
				return this._Director;
			}
			set
			{
				if ((this._Director != value))
				{
					this._Director = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> Start_Time
		{
			get
			{
				return this._Start_Time;
			}
			set
			{
				if ((this._Start_Time != value))
				{
					this._Start_Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> End_Time
		{
			get
			{
				return this._End_Time;
			}
			set
			{
				if ((this._End_Time != value))
				{
					this._End_Time = value;
				}
			}
		}
	}
	
	public partial class Fn_SumTotalCostResult
	{
		
		private System.Nullable<int> _Total;
		
		public Fn_SumTotalCostResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Int")]
		public System.Nullable<int> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class Fn_UserBookedResult
	{
		
		private string _Reservation_ID;
		
		private string _Movie_Title;
		
		private System.Nullable<int> _Seat;
		
		private System.Nullable<System.DateTime> _Date;
		
		private System.Nullable<System.TimeSpan> _Start_Time;
		
		private System.Nullable<System.TimeSpan> _End_Time;
		
		private string _Room;
		
		public Fn_UserBookedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reservation_ID", DbType="NVarChar(50)")]
		public string Reservation_ID
		{
			get
			{
				return this._Reservation_ID;
			}
			set
			{
				if ((this._Reservation_ID != value))
				{
					this._Reservation_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_Title", DbType="NVarChar(50)")]
		public string Movie_Title
		{
			get
			{
				return this._Movie_Title;
			}
			set
			{
				if ((this._Movie_Title != value))
				{
					this._Movie_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seat", DbType="Int")]
		public System.Nullable<int> Seat
		{
			get
			{
				return this._Seat;
			}
			set
			{
				if ((this._Seat != value))
				{
					this._Seat = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Start_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> Start_Time
		{
			get
			{
				return this._Start_Time;
			}
			set
			{
				if ((this._Start_Time != value))
				{
					this._Start_Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_End_Time", DbType="Time")]
		public System.Nullable<System.TimeSpan> End_Time
		{
			get
			{
				return this._End_Time;
			}
			set
			{
				if ((this._End_Time != value))
				{
					this._End_Time = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room", DbType="NVarChar(50)")]
		public string Room
		{
			get
			{
				return this._Room;
			}
			set
			{
				if ((this._Room != value))
				{
					this._Room = value;
				}
			}
		}
	}
	
	public partial class Fn_UserCommentedResult
	{
		
		private string _Reservation_ID;
		
		private string _Movie_Title;
		
		private System.Nullable<int> _Rating_Point;
		
		private string _Comment;
		
		public Fn_UserCommentedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Reservation_ID", DbType="NVarChar(50)")]
		public string Reservation_ID
		{
			get
			{
				return this._Reservation_ID;
			}
			set
			{
				if ((this._Reservation_ID != value))
				{
					this._Reservation_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Movie_Title", DbType="NVarChar(50)")]
		public string Movie_Title
		{
			get
			{
				return this._Movie_Title;
			}
			set
			{
				if ((this._Movie_Title != value))
				{
					this._Movie_Title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rating_Point", DbType="Int")]
		public System.Nullable<int> Rating_Point
		{
			get
			{
				return this._Rating_Point;
			}
			set
			{
				if ((this._Rating_Point != value))
				{
					this._Rating_Point = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(50)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
	}
	
	public partial class Fn_UserInformationResult
	{
		
		private string _UserName;
		
		private System.Nullable<int> _Balance;
		
		private System.Nullable<int> _Point;
		
		private System.Nullable<bool> _isVIP;
		
		private System.Nullable<int> _Expense;
		
		public Fn_UserInformationResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this._UserName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Int")]
		public System.Nullable<int> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this._Balance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Point", DbType="Int")]
		public System.Nullable<int> Point
		{
			get
			{
				return this._Point;
			}
			set
			{
				if ((this._Point != value))
				{
					this._Point = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isVIP", DbType="Bit")]
		public System.Nullable<bool> isVIP
		{
			get
			{
				return this._isVIP;
			}
			set
			{
				if ((this._isVIP != value))
				{
					this._isVIP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Expense", DbType="Int")]
		public System.Nullable<int> Expense
		{
			get
			{
				return this._Expense;
			}
			set
			{
				if ((this._Expense != value))
				{
					this._Expense = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
